import { describe, expect, it } from "vitest";
import { parsePLYHeader } from "./header";
import { DEFAULT_PLY_LIMITS } from "./types";
import { buildPLY, expectPLYError, simpleTriangleFaceElement, simpleTriangleVertexElement, textToBuffer } from "./test-fixtures";

const LIMITS = DEFAULT_PLY_LIMITS;

describe("parsePLYHeader", () => {
  it("parses a well-formed ASCII header with vertex and face elements", () => {
    const buffer = buildPLY({ format: "ascii", elements: [simpleTriangleVertexElement(), simpleTriangleFaceElement()] });
    const { header, bodyOffset } = parsePLYHeader(buffer, LIMITS);
    expect(header.format).toBe("ascii");
    expect(header.elements).toHaveLength(2);
    expect(header.elements[0].name).toBe("vertex");
    expect(header.elements[0].properties.map((p) => p.name)).toEqual(["x", "y", "z"]);
    expect(header.elements[1].name).toBe("face");
    expect(bodyOffset).toBeGreaterThan(0);
  });

  it("parses binary_little_endian and binary_big_endian format lines", () => {
    const le = buildPLY({ format: "binary_little_endian", elements: [simpleTriangleVertexElement(), simpleTriangleFaceElement()] });
    expect(parsePLYHeader(le, LIMITS).header.format).toBe("binary_little_endian");

    const be = buildPLY({ format: "binary_big_endian", elements: [simpleTriangleVertexElement(), simpleTriangleFaceElement()] });
    expect(parsePLYHeader(be, LIMITS).header.format).toBe("binary_big_endian");
  });

  it("tolerates LF, CRLF and CR line endings", () => {
    const lines = ["ply", "format ascii 1.0", "element vertex 0", "end_header"];
    for (const ending of ["\n", "\r\n", "\r"]) {
      const buffer = textToBuffer(lines.join(ending) + ending);
      const { header } = parsePLYHeader(buffer, LIMITS);
      expect(header.elements).toEqual([{ name: "vertex", count: 0, properties: [] }]);
    }
  });

  it("skips comment and obj_info lines", () => {
    const buffer = buildPLY({
      format: "ascii",
      comments: ["generated by a test", "obj_info tool test-tool"],
      elements: [{ name: "vertex", count: 0, properties: [], rows: [] }],
    });
    const { header } = parsePLYHeader(buffer, LIMITS);
    expect(header.elements).toHaveLength(1);
  });

  it("parses list properties with distinct count and item types", () => {
    const buffer = buildPLY({ format: "ascii", elements: [simpleTriangleVertexElement(), simpleTriangleFaceElement()] });
    const { header } = parsePLYHeader(buffer, LIMITS);
    const faceProp = header.elements[1].properties[0];
    expect(faceProp).toEqual({ kind: "list", countType: "uint8", itemType: "int32", name: "vertex_indices" });
  });

  it("rejects a file whose first line isn't 'ply'", () => {
    const buffer = textToBuffer("not-ply\nformat ascii 1.0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_MAGIC_INVALID");
  });

  it("rejects a missing format line", () => {
    const buffer = textToBuffer("ply\nelement vertex 0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_FORMAT_MISSING");
  });

  it("rejects a duplicate format line", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nformat ascii 1.0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_FORMAT_DUPLICATE");
  });

  it("rejects an unsupported format keyword", () => {
    const buffer = textToBuffer("ply\nformat xml 1.0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_FORMAT_UNSUPPORTED");
  });

  it("rejects an unsupported format version", () => {
    const buffer = textToBuffer("ply\nformat ascii 2.0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_FORMAT_UNSUPPORTED");
  });

  it("rejects a property line before any element", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nproperty float x\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_PROPERTY_BEFORE_ELEMENT");
  });

  it("rejects a malformed element line", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex not-a-number\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_ELEMENT_INVALID");
  });

  it("rejects a negative element count", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex -1\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_ELEMENT_INVALID");
  });

  it("rejects a duplicate element name", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex 0\nelement vertex 0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_ELEMENT_DUPLICATE");
  });

  it("rejects an unrecognized scalar type token", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex 1\nproperty imaginary x\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_PROPERTY_INVALID");
  });

  it("rejects a duplicate property name on one element", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex 1\nproperty float x\nproperty float x\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_PROPERTY_DUPLICATE");
  });

  it("rejects an unrecognized header keyword", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nbogus keyword\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_UNKNOWN_KEYWORD");
  });

  it("rejects a header that never reaches end_header", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex 0\n");
    expectPLYError(() => parsePLYHeader(buffer, LIMITS), "PLY_HEADER_UNTERMINATED");
  });

  it("rejects a header exceeding the safety byte budget", () => {
    const buffer = textToBuffer("ply\n" + "comment padding\n".repeat(100000));
    expectPLYError(() => parsePLYHeader(buffer, { ...LIMITS, maxHeaderBytes: 1000 }), "PLY_HEADER_TOO_LARGE");
  });

  it("rejects more elements than the configured limit", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement a 0\nelement b 0\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, { ...LIMITS, maxElements: 1 }), "PLY_ELEMENT_LIMIT_EXCEEDED");
  });

  it("rejects more properties on one element than the configured limit", () => {
    const buffer = textToBuffer("ply\nformat ascii 1.0\nelement vertex 1\nproperty float x\nproperty float y\nend_header\n");
    expectPLYError(() => parsePLYHeader(buffer, { ...LIMITS, maxPropertiesPerElement: 1 }), "PLY_PROPERTY_LIMIT_EXCEEDED");
  });
});
