/**
 * Slicer comment adapters — recognizes REPRESENTATIVE, commonly-observed
 * comment conventions from Cura, PrusaSlicer, OrcaSlicer and Bambu
 * Studio. This is a documented semantic subset (per this project's own
 * supported-dialect scope), not a guarantee of matching every version or
 * configuration of these slicers — an unmatched comment is simply
 * ignored, never guessed at. Every numeric value is validated
 * (`Number.isFinite`) before being trusted; a malformed or non-finite
 * value is reported as `null`, never a wrong number.
 */
import type { GCodeComment } from "./tokenizer";

export type SlicerId = "cura" | "prusaslicer" | "orcaslicer" | "bambustudio";

export interface SlicerBounds {
  minX?: number;
  minY?: number;
  minZ?: number;
  maxX?: number;
  maxY?: number;
  maxZ?: number;
}

export interface SlicerCommentSignal {
  slicerHint: SlicerId | null;
  layerMarker: boolean;
  layerIndex: number | null;
  layerZ: number | null;
  layerHeight: number | null;
  featureLabel: string | null;
  estimatedPrintTimeSeconds: number | null;
  filamentUsedMm: number | null;
  layerCount: number | null;
  bounds: SlicerBounds | null;
}

function emptySignal(): SlicerCommentSignal {
  return {
    slicerHint: null,
    layerMarker: false,
    layerIndex: null,
    layerZ: null,
    layerHeight: null,
    featureLabel: null,
    estimatedPrintTimeSeconds: null,
    filamentUsedMm: null,
    layerCount: null,
    bounds: null,
  };
}

function validNumber(text: string): number | null {
  const n = Number(text);
  return Number.isFinite(n) ? n : null;
}

/** Parses a PrusaSlicer/OrcaSlicer-style duration string, e.g. "1h 23m 45s" or "45s" or "2d 3h", into total seconds. */
function parseDurationString(text: string): number | null {
  const re = /(\d+)\s*(d|h|m|s)/gi;
  let match: RegExpExecArray | null;
  let total = 0;
  let matched = false;
  while ((match = re.exec(text)) !== null) {
    matched = true;
    const value = Number(match[1]);
    if (!Number.isFinite(value)) return null;
    const unit = match[2].toLowerCase();
    const multiplier = unit === "d" ? 86400 : unit === "h" ? 3600 : unit === "m" ? 60 : 1;
    total += value * multiplier;
  }
  return matched ? total : null;
}

export function parseSlicerComment(comment: GCodeComment): SlicerCommentSignal {
  const signal = emptySignal();
  const text = comment.text.trim();

  if (/Cura_SteamEngine/i.test(text)) signal.slicerHint = "cura";
  else if (/generated by PrusaSlicer/i.test(text)) signal.slicerHint = "prusaslicer";
  else if (/generated by OrcaSlicer/i.test(text)) signal.slicerHint = "orcaslicer";
  else if (/generated by BambuStudio/i.test(text)) signal.slicerHint = "bambustudio";

  let m: RegExpMatchArray | null;

  if ((m = text.match(/^LAYER:(-?\d+)$/i))) {
    signal.layerMarker = true;
    signal.layerIndex = validNumber(m[1]) !== null ? Math.trunc(validNumber(m[1])!) : null;
  } else if (/^LAYER_CHANGE$/i.test(text) || /^CHANGE_LAYER$/i.test(text)) {
    signal.layerMarker = true;
  }

  if ((m = text.match(/^LAYER_COUNT:(\d+)$/i))) {
    signal.layerCount = validNumber(m[1]);
  }

  if ((m = text.match(/^Z:([+-]?[\d.]+)$/i))) {
    signal.layerZ = validNumber(m[1]);
  }

  if ((m = text.match(/^HEIGHT:([+-]?[\d.]+)$/i))) {
    signal.layerHeight = validNumber(m[1]);
  }

  if ((m = text.match(/^TYPE:\s*(.+)$/i))) {
    signal.featureLabel = m[1].trim();
  } else if ((m = text.match(/^FEATURE:\s*(.+)$/i))) {
    signal.featureLabel = m[1].trim();
  }

  if ((m = text.match(/^TIME:([\d.]+)$/i))) {
    signal.estimatedPrintTimeSeconds = validNumber(m[1]);
  } else if ((m = text.match(/estimated printing time.*?=\s*(.+)$/i))) {
    signal.estimatedPrintTimeSeconds = parseDurationString(m[1]);
  }

  if ((m = text.match(/^Filament used:\s*([\d.]+)\s*m\b/i))) {
    const meters = validNumber(m[1]);
    signal.filamentUsedMm = meters !== null ? meters * 1000 : null;
  } else if ((m = text.match(/filament used \[mm\]\s*=\s*([\d.]+)/i))) {
    signal.filamentUsedMm = validNumber(m[1]);
  }

  const boundsMatch = text.match(/^(MINX|MINY|MINZ|MAXX|MAXY|MAXZ):([+-]?[\d.]+)$/i);
  if (boundsMatch) {
    const value = validNumber(boundsMatch[2]);
    if (value !== null) {
      const key = boundsMatch[1].toLowerCase();
      const fieldMap: Record<string, keyof SlicerBounds> = { minx: "minX", miny: "minY", minz: "minZ", maxx: "maxX", maxy: "maxY", maxz: "maxZ" };
      signal.bounds = { [fieldMap[key]]: value };
    }
  }

  return signal;
}
