import { describe, expect, it } from "vitest";
import { tokenizeLine } from "./tokenizer";
import { parseSlicerComment } from "./comments";

function signalFor(line: string) {
  const t = tokenizeLine(line);
  if (!t.comment) throw new Error("test line has no comment");
  return parseSlicerComment(t.comment);
}

describe("parseSlicerComment — Cura", () => {
  it("recognizes the Cura generator header as a slicer hint", () => {
    expect(signalFor(";Generated with Cura_SteamEngine 5.6.0").slicerHint).toBe("cura");
  });

  it("recognizes an explicit LAYER marker", () => {
    const s = signalFor(";LAYER:3");
    expect(s.layerMarker).toBe(true);
    expect(s.layerIndex).toBe(3);
  });

  it("recognizes LAYER_COUNT", () => {
    expect(signalFor(";LAYER_COUNT:120").layerCount).toBe(120);
  });

  it("recognizes a TYPE feature marker", () => {
    expect(signalFor(";TYPE:WALL-OUTER").featureLabel).toBe("WALL-OUTER");
  });

  it("recognizes TIME as an estimated print time in seconds", () => {
    expect(signalFor(";TIME:5423").estimatedPrintTimeSeconds).toBe(5423);
  });

  it("recognizes filament used in meters and converts to millimeters", () => {
    expect(signalFor(";Filament used: 12.5m").filamentUsedMm).toBeCloseTo(12500, 3);
  });

  it("recognizes model bounds", () => {
    expect(signalFor(";MINX:-10.5").bounds).toEqual({ minX: -10.5 });
    expect(signalFor(";MAXZ:35").bounds).toEqual({ maxZ: 35 });
  });
});

describe("parseSlicerComment — PrusaSlicer / OrcaSlicer", () => {
  it("recognizes the PrusaSlicer generator header", () => {
    expect(signalFor("; generated by PrusaSlicer 2.7.0 on 2024-01-01").slicerHint).toBe("prusaslicer");
  });

  it("recognizes the OrcaSlicer generator header", () => {
    expect(signalFor("; generated by OrcaSlicer 1.9.0").slicerHint).toBe("orcaslicer");
  });

  it("recognizes a LAYER_CHANGE marker", () => {
    expect(signalFor(";LAYER_CHANGE").layerMarker).toBe(true);
  });

  it("recognizes a Z: layer height comment", () => {
    expect(signalFor(";Z:0.4").layerZ).toBe(0.4);
  });

  it("recognizes a HEIGHT: layer height comment", () => {
    expect(signalFor(";HEIGHT:0.2").layerHeight).toBe(0.2);
  });

  it("recognizes a TYPE feature marker with a slicer-specific label", () => {
    expect(signalFor(";TYPE:External perimeter").featureLabel).toBe("External perimeter");
  });

  it("recognizes an estimated printing time string and converts it to seconds", () => {
    const s = signalFor("; estimated printing time (normal mode) = 1h 23m 45s");
    expect(s.estimatedPrintTimeSeconds).toBe(1 * 3600 + 23 * 60 + 45);
  });

  it("recognizes filament used in millimeters directly", () => {
    expect(signalFor("; filament used [mm] = 3200.5").filamentUsedMm).toBeCloseTo(3200.5, 3);
  });
});

describe("parseSlicerComment — Bambu Studio", () => {
  it("recognizes the BambuStudio generator header", () => {
    expect(signalFor("; generated by BambuStudio 1.9.0").slicerHint).toBe("bambustudio");
  });

  it("recognizes a CHANGE_LAYER marker", () => {
    expect(signalFor("; CHANGE_LAYER").layerMarker).toBe(true);
  });

  it("recognizes a FEATURE marker as the feature label", () => {
    expect(signalFor("; FEATURE: Inner wall").featureLabel).toBe("Inner wall");
  });
});

describe("parseSlicerComment — untrusted/unknown comments", () => {
  it("returns an all-null signal for an ordinary human comment, never guessing", () => {
    const s = signalFor("; just chatting about this print");
    expect(s.slicerHint).toBeNull();
    expect(s.layerMarker).toBe(false);
    expect(s.featureLabel).toBeNull();
  });

  it("never throws on a malformed numeric comment value, and doesn't report a bogus number", () => {
    expect(() => signalFor(";LAYER:not-a-number")).not.toThrow();
    expect(signalFor(";LAYER:not-a-number").layerIndex).toBeNull();
  });

  it("rejects a non-finite numeric comment value rather than trusting it", () => {
    expect(signalFor(";TIME:Infinity").estimatedPrintTimeSeconds).toBeNull();
  });
});
