/**
 * Deterministic G-code fixtures used only by tests — never imported by
 * app code. Kept small and human-readable except where a stress case
 * genuinely needs to be large.
 */

export function chunkString(text: string, chunkSize: number): Uint8Array[] {
  const bytes = new TextEncoder().encode(text);
  const out: Uint8Array[] = [];
  for (let i = 0; i < bytes.length; i += chunkSize) out.push(bytes.slice(i, i + chunkSize));
  return out;
}

/** A minimal two-layer square print, absolute XYZ/E, no comments at all. */
export function basicAbsoluteExtrusion(): string {
  return [
    "G21",
    "G90",
    "M82",
    "G1 Z0.2 F300",
    "G1 X0 Y0 F1500",
    "G1 X10 Y0 E1 F1200",
    "G1 X10 Y10 E2",
    "G1 X0 Y10 E3",
    "G1 X0 Y0 E4",
    "G1 Z0.4 F300",
    "G1 X0 Y0 F1500",
    "G1 X10 Y0 E5 F1200",
    "G1 X10 Y10 E6",
    "G1 X0 Y10 E7",
    "G1 X0 Y0 E8",
    "",
  ].join("\n");
}

/** Relative XYZ and relative E (M83), a single square layer. */
export function relativeXYZAndExtrusion(): string {
  return ["G21", "G91", "M83", "G1 X10 F1500", "G1 X0 Y10 E1 F1200", "G1 X-10 Y0 E1", "G1 X0 Y-10 E1", ""].join("\n");
}

/** G92 resets that must never create false movement. */
export function g92ResetFixture(): string {
  return ["G21", "G90", "G1 X10 Y10 F1500", "G92 X0 Y0", "G1 X5 Y5 E1 F1200", ""].join("\n");
}

/** Mixed G90/G91/M82/M83 interaction on the same file. */
export function mixedPositioningModes(): string {
  return ["G21", "G90", "M83", "G1 X10 E1 F1200", "G91", "G1 X5 E0.5", "G90", "G1 X20 E0.5", ""].join("\n");
}

/** Retract, travel, then prime, then resume extrusion — a realistic travel move sequence. */
export function retractPrimeSequence(): string {
  return ["G21", "G90", "M83", "G1 X10 E1 F1200", "G1 E-1 F1800", "G0 X30 Y30 F6000", "G1 E1 F1800", "G1 X40 E1", ""].join("\n");
}

/** Two tools, each with independent E state, switched back and forth. */
export function twoToolFixture(): string {
  return ["G21", "G90", "M83", "T0", "G1 X10 E1 F1200", "T1", "G1 X10 Y10 E2", "T0", "G1 X20 E1", "T1", "G1 X10 Y20 E1", ""].join("\n");
}

/** Inch-mode coordinates and feed rate. */
export function inchModeFixture(): string {
  return ["G20", "G90", "M82", "G1 X1 Y1 F10", "G1 X2 Y2 E0.1", ""].join("\n");
}

/** A quarter-circle arc in each of the three planes. */
export function xyArcFixture(): string {
  return ["G21", "G90", "M83", "G17", "G1 X10 Y0 F1500", "G3 X0 Y10 I-10 J0 E1 F1200", ""].join("\n");
}

export function xzArcFixture(): string {
  return ["G21", "G90", "M83", "G18", "G1 X10 Y0 Z0 F1500", "G3 X0 Z10 I-10 K0 E1 F1200", ""].join("\n");
}

export function yzArcFixture(): string {
  return ["G21", "G90", "M83", "G19", "G1 X0 Y10 Z0 F1500", "G3 Y0 Z10 J-10 K0 E1 F1200", ""].join("\n");
}

/** A helical (Z-rising) arc. */
export function helicalArcFixture(): string {
  return ["G21", "G90", "M83", "G17", "G1 X10 Y0 Z0 F1500", "G3 X-10 Y0 Z2 I-10 J0 E2 F1200", ""].join("\n");
}

/** An arc whose geometry is invalid (endpoint not equidistant from the declared center). */
export function invalidArcFixture(): string {
  return ["G21", "G90", "M83", "G1 X0 Y0 F1500", "G3 X5 Y5 I10 J0 E1 F1200", "G1 X20 Y20 E1", ""].join("\n");
}

/** Checksummed, numbered lines — all valid. */
export function checksummedLinesFixture(): string {
  const lines = ["G21", "G90 G1 X10 Y10 F1500"];
  const out: string[] = [];
  let n = 0;
  for (const body of lines) {
    const withNumber = `N${n} ${body}`;
    let sum = 0;
    for (const ch of withNumber) sum ^= ch.charCodeAt(0);
    out.push(`${withNumber}*${sum}`);
    n++;
  }
  return out.join("\n") + "\n";
}

/** Cura-style comments: LAYER markers, TYPE markers, TIME, filament used. */
export function curaCommentsFixture(): string {
  return [
    ";Generated with Cura_SteamEngine 5.6.0",
    ";LAYER_COUNT:2",
    ";LAYER:0",
    "G21",
    "G90",
    "M82",
    ";TYPE:WALL-OUTER",
    "G1 Z0.2 F300",
    "G1 X0 Y0 F1500",
    "G1 X10 Y0 E1 F1200",
    ";LAYER:1",
    "G1 Z0.4 F300",
    "G1 X10 Y10 E2",
    ";TIME:120",
    ";Filament used: 0.5m",
    "",
  ].join("\n");
}

/** PrusaSlicer-style comments: generator header, LAYER_CHANGE + Z:/HEIGHT:, TYPE, estimated time, filament used. */
export function prusaSlicerCommentsFixture(): string {
  return [
    "; generated by PrusaSlicer 2.7.0 on 2024-01-01",
    "G21",
    "G90",
    "M83",
    ";LAYER_CHANGE",
    ";Z:0.2",
    ";HEIGHT:0.2",
    ";TYPE:External perimeter",
    "G1 X0 Y0 F1500",
    "G1 X10 Y0 E1 F1200",
    ";LAYER_CHANGE",
    ";Z:0.4",
    ";HEIGHT:0.2",
    "G1 X10 Y10 E1",
    "; estimated printing time (normal mode) = 12m 30s",
    "; filament used [mm] = 850.2",
    "",
  ].join("\n");
}

/** OrcaSlicer/Bambu Studio-style comments: generator header, CHANGE_LAYER, FEATURE. */
export function orcaBambuCommentsFixture(): string {
  return [
    "; generated by OrcaSlicer 1.9.0",
    "G21",
    "G90",
    "M83",
    "; CHANGE_LAYER",
    "; FEATURE: Outer wall",
    "G1 X0 Y0 F1500",
    "G1 X10 Y0 E1 F1200",
    "; CHANGE_LAYER",
    "; FEATURE: Sparse infill",
    "G1 X10 Y10 E1",
    "",
  ].join("\n");
}

/** No layer/feature comments at all — layers must be inferred. */
export function noCommentsFixture(): string {
  return basicAbsoluteExtrusion();
}

/** A Z-hop: lift, travel, come back down at the SAME layer height. */
export function zHopFixture(): string {
  return ["G21", "G90", "M83", "G1 X0 Y0 Z0.2 F1500", "G1 X10 Y0 E1 F1200", "G1 Z0.7 F600", "G1 X20 Y20 F6000", "G1 Z0.2 F600", "G1 X30 Y20 E1 F1200", ""].join(
    "\n",
  );
}

/** Variable layer heights: 0.2, 0.3, 0.15. */
export function variableLayerHeightsFixture(): string {
  return ["G21", "G90", "M83", "G1 X0 Y0 Z0.2 F1500", "G1 X10 Y0 E1 F1200", "G1 Z0.5 F600", "G1 X20 Y0 E1", "G1 Z0.65 F600", "G1 X30 Y0 E1", ""].join("\n");
}

/** Spiral/vase-mode motion: Z rises a tiny amount on every single extruding move. */
export function spiralVaseFixture(lines = 60): string {
  const out = ["G21", "G90", "M83"];
  for (let i = 0; i < lines; i++) {
    const z = (0.2 + i * 0.004).toFixed(4);
    out.push(`G1 X${(i % 10).toFixed(1)} Y0 Z${z} E0.1 F1200`);
  }
  out.push("");
  return out.join("\n");
}

/** Unsupported motion command (G5 spline) mixed with otherwise-valid motion. */
export function unsupportedCommandFixture(): string {
  return ["G21", "G90", "M83", "G1 X0 Y0 F1500", "G5 X10 Y10 I1 J1 P1 Q1", "G1 X20 Y20 E1 F1200", ""].join("\n");
}

/** Malformed numeric tokens mixed into otherwise-valid lines. */
export function malformedNumbersFixture(): string {
  return ["G21", "G90", "M83", "G1 X10.5.3 Y0 F1500", "G1 X20 Y Z10 E1 F1200", ""].join("\n");
}

/** A single line far longer than any reasonable G-code line (stress case). */
export function hugeLineFixture(): string {
  const comment = ";" + "x".repeat(50_000);
  return ["G21", "G90", comment, "G1 X10 F1500", ""].join("\n");
}

/** A large file for cancellation testing. */
export function largeCancellationFixture(moves = 5000): string {
  const out = ["G21", "G90", "M83"];
  for (let i = 0; i < moves; i++) out.push(`G1 X${i % 100} Y${(i * 2) % 100} E0.1 F1200`);
  out.push("");
  return out.join("\n");
}
