/**
 * Registry of tools this product plans to ship. This is a planning
 * artifact for future phases — Phase 1 does not generate any pages from
 * it. Only list a tool here once it is genuinely planned; do not add
 * placeholder entries just to pad the catalog.
 */
export type ToolCategory = "viewer" | "converter" | "diagnostic" | "repair" | "optimizer";
export type ToolStatus = "planned" | "development" | "ready";

export interface ToolDefinition {
  id: string;
  name: string;
  /** Future public route, e.g. "/stl-viewer/". Not yet built in Phase 1. */
  path: string;
  category: ToolCategory;
  description: string;
  inputFormats: string[];
  outputFormats?: string[];
  relatedToolIds?: string[];
  status: ToolStatus;
}

export const toolRegistry: ToolDefinition[] = [
  {
    id: "stl-viewer",
    name: "STL Viewer",
    path: "/stl-viewer/",
    category: "viewer",
    description: "Inspect STL geometry, dimensions and triangle count in your browser.",
    inputFormats: ["stl"],
    relatedToolIds: [
      "viewer",
      "stl-repair",
      "stl-checker",
      "stl-validator",
      "stl-to-obj",
      "stl-to-3mf",
      "obj-viewer",
      "3mf-viewer",
      "3mf-to-stl",
      "obj-to-stl",
      "glb-viewer",
      "glb-to-stl",
      "ply-to-stl",
      "ply-viewer",
      "fbx-viewer",
      "reduce-stl-size",
      "simplify-stl",
      "stl-triangle-reducer",
      "gcode-viewer",
      "gcode-visualizer",
      "gcode-simulator",
      "gcode-layer-viewer",
      "gcode-toolpath-viewer",
    ],
    status: "ready",
  },
  {
    id: "obj-viewer",
    name: "OBJ Viewer",
    path: "/obj-viewer/",
    category: "viewer",
    description: "Inspect OBJ geometry, objects, groups and normals in your browser.",
    inputFormats: ["obj"],
    relatedToolIds: ["viewer", "obj-to-stl", "stl-viewer", "3mf-viewer", "glb-viewer", "ply-viewer", "fbx-viewer"],
    status: "ready",
  },
  {
    id: "3mf-viewer",
    name: "3MF Viewer",
    path: "/3mf-viewer/",
    category: "viewer",
    description: "Inspect 3MF objects, components, colors and units in your browser.",
    inputFormats: ["3mf"],
    relatedToolIds: ["viewer", "3mf-to-stl", "stl-viewer", "obj-viewer", "glb-viewer", "ply-viewer", "fbx-viewer"],
    status: "ready",
  },
  {
    id: "3mf-to-stl",
    name: "3MF to STL",
    path: "/3mf-to-stl/",
    category: "converter",
    description: "Convert 3MF models to STL without uploading the file.",
    inputFormats: ["3mf"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-viewer", "3mf-viewer"],
    status: "ready",
  },
  {
    id: "obj-to-stl",
    name: "OBJ to STL",
    path: "/obj-to-stl/",
    category: "converter",
    description: "Convert OBJ models to STL locally in your browser.",
    inputFormats: ["obj"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-viewer", "obj-viewer"],
    status: "ready",
  },
  {
    id: "glb-viewer",
    name: "GLB Viewer",
    path: "/glb-viewer/",
    category: "viewer",
    description: "Inspect GLB scenes, materials and embedded textures in your browser.",
    inputFormats: ["glb"],
    relatedToolIds: ["viewer", "glb-to-stl", "stl-viewer", "obj-viewer", "3mf-viewer", "ply-viewer", "fbx-viewer"],
    status: "ready",
  },
  {
    id: "glb-to-stl",
    name: "GLB to STL",
    path: "/glb-to-stl/",
    category: "converter",
    description: "Convert GLB models to STL locally in your browser.",
    inputFormats: ["glb"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-viewer", "glb-viewer"],
    status: "ready",
  },
  {
    id: "stl-checker",
    name: "STL Checker",
    path: "/stl-checker/",
    category: "diagnostic",
    description: "Detect non-manifold edges, holes, winding conflicts, self-intersections and flipped normals in an STL file.",
    inputFormats: ["stl"],
    relatedToolIds: ["stl-validator", "stl-repair", "stl-viewer", "make-stl-watertight", "repair-non-manifold-stl", "viewer", "reduce-stl-size", "simplify-stl", "stl-triangle-reducer", "gcode-viewer"],
    status: "ready",
  },
  {
    id: "stl-validator",
    name: "STL Validator",
    path: "/stl-validator/",
    category: "diagnostic",
    description: "Validate an STL file's mesh topology against a precise, disclosed watertightness rule set.",
    inputFormats: ["stl"],
    relatedToolIds: ["stl-checker", "stl-repair", "stl-viewer", "make-stl-watertight", "repair-non-manifold-stl"],
    status: "ready",
  },
  {
    id: "stl-repair",
    name: "STL Repair",
    path: "/stl-repair/",
    category: "repair",
    description: "Repair holes, flipped normals, duplicate faces and non-manifold geometry in an STL file.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["make-stl-watertight", "repair-non-manifold-stl", "stl-checker", "stl-validator", "stl-viewer", "viewer", "reduce-stl-size", "simplify-stl", "stl-triangle-reducer", "gcode-viewer"],
    status: "ready",
  },
  {
    id: "make-stl-watertight",
    name: "Make STL Watertight",
    path: "/make-stl-watertight/",
    category: "repair",
    description: "Close holes and fix boundary gaps to make an STL file watertight, locally in your browser.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-repair", "repair-non-manifold-stl", "stl-checker", "stl-validator"],
    status: "ready",
  },
  {
    id: "repair-non-manifold-stl",
    name: "Repair Non-Manifold STL",
    path: "/repair-non-manifold-stl/",
    category: "repair",
    description: "Detect and safely resolve non-manifold edges and duplicate geometry in an STL file.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-repair", "make-stl-watertight", "stl-checker", "stl-validator"],
    status: "ready",
  },
  {
    id: "stl-to-obj",
    name: "STL to OBJ",
    path: "/stl-to-obj/",
    category: "converter",
    description: "Convert an STL model to OBJ locally in your browser.",
    inputFormats: ["stl"],
    outputFormats: ["obj"],
    relatedToolIds: ["stl-viewer"],
    status: "ready",
  },
  {
    id: "stl-to-3mf",
    name: "STL to 3MF",
    path: "/stl-to-3mf/",
    category: "converter",
    description: "Convert an STL model to 3MF locally in your browser.",
    inputFormats: ["stl"],
    outputFormats: ["3mf"],
    relatedToolIds: ["stl-viewer"],
    status: "ready",
  },
  {
    id: "ply-to-stl",
    name: "PLY to STL",
    path: "/ply-to-stl/",
    category: "converter",
    description: "Convert PLY (Polygon File Format) models to STL locally in your browser.",
    inputFormats: ["ply"],
    outputFormats: ["stl"],
    relatedToolIds: ["stl-viewer", "ply-viewer"],
    status: "ready",
  },
  {
    id: "ply-viewer",
    name: "PLY Viewer",
    path: "/ply-viewer/",
    category: "viewer",
    description: "Inspect PLY meshes and point clouds in your browser.",
    inputFormats: ["ply"],
    relatedToolIds: ["viewer", "ply-to-stl", "stl-viewer", "obj-viewer", "3mf-viewer", "glb-viewer", "fbx-viewer"],
    status: "ready",
  },
  {
    id: "fbx-viewer",
    name: "FBX Viewer",
    path: "/fbx-viewer/",
    category: "viewer",
    description: "Inspect static binary FBX meshes, materials and embedded textures in your browser.",
    inputFormats: ["fbx"],
    relatedToolIds: ["viewer", "stl-viewer", "obj-viewer", "3mf-viewer", "glb-viewer", "ply-viewer"],
    status: "ready",
  },
  {
    id: "viewer",
    name: "3D File Viewer",
    path: "/viewer/",
    category: "viewer",
    description: "Automatically detects and opens STL, OBJ, 3MF, GLB, PLY and binary FBX files in one universal browser-based viewer.",
    inputFormats: ["stl", "obj", "3mf", "glb", "ply", "fbx"],
    relatedToolIds: [
      "stl-viewer",
      "obj-viewer",
      "3mf-viewer",
      "glb-viewer",
      "ply-viewer",
      "fbx-viewer",
      "stl-checker",
      "stl-repair",
      "gcode-viewer",
      "gcode-visualizer",
      "gcode-simulator",
      "gcode-layer-viewer",
      "gcode-toolpath-viewer",
    ],
    status: "ready",
  },
  {
    id: "reduce-stl-size",
    name: "Reduce STL File Size",
    path: "/reduce-stl-file-size/",
    category: "optimizer",
    description: "Simplify an STL model's triangle count to shrink its file size locally in your browser.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["simplify-stl", "stl-triangle-reducer", "stl-viewer", "stl-checker", "stl-repair", "gcode-viewer"],
    status: "ready",
  },
  {
    id: "simplify-stl",
    name: "Simplify STL",
    path: "/simplify-stl/",
    category: "optimizer",
    description: "Simplify an STL mesh with topology-safe edge-collapse reduction, preserving boundaries and shells.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["reduce-stl-size", "stl-triangle-reducer", "stl-viewer", "stl-checker", "stl-repair"],
    status: "ready",
  },
  {
    id: "stl-triangle-reducer",
    name: "STL Triangle Reducer",
    path: "/stl-triangle-reducer/",
    category: "optimizer",
    description: "Reduce an STL file's triangle count to an explicit target to fix slicer facet-count limits.",
    inputFormats: ["stl"],
    outputFormats: ["stl"],
    relatedToolIds: ["reduce-stl-size", "simplify-stl", "stl-viewer", "stl-checker", "stl-repair"],
    status: "ready",
  },
  {
    id: "gcode-viewer",
    name: "G-code Viewer",
    path: "/gcode-viewer/",
    category: "viewer",
    description: "Open a G-code file and inspect its statistics, layers, tools and time estimates in your browser.",
    inputFormats: ["gcode"],
    relatedToolIds: ["gcode-visualizer", "gcode-simulator", "gcode-layer-viewer", "gcode-toolpath-viewer", "viewer", "stl-viewer", "stl-checker", "stl-repair", "reduce-stl-size"],
    status: "ready",
  },
  {
    id: "gcode-visualizer",
    name: "G-code Visualizer",
    path: "/gcode-visualizer/",
    category: "viewer",
    description: "Render a G-code file's categorized toolpaths — by feature, movement type, tool or feed rate — locally in your browser.",
    inputFormats: ["gcode"],
    relatedToolIds: ["gcode-viewer", "gcode-simulator", "gcode-layer-viewer", "gcode-toolpath-viewer", "viewer", "stl-viewer"],
    status: "ready",
  },
  {
    id: "gcode-simulator",
    name: "G-code Simulator",
    path: "/gcode-simulator/",
    category: "viewer",
    description: "Play back a G-code file's parsed tool movement visually, locally in your browser — a visual simulator, never a firmware or printer connection.",
    inputFormats: ["gcode"],
    relatedToolIds: ["gcode-viewer", "gcode-visualizer", "gcode-layer-viewer", "gcode-toolpath-viewer", "viewer", "stl-viewer"],
    status: "ready",
  },
  {
    id: "gcode-layer-viewer",
    name: "G-code Layer Viewer",
    path: "/gcode-layer-viewer/",
    category: "viewer",
    description: "Inspect a G-code file layer by layer — single-layer, cumulative or full-model views — locally in your browser.",
    inputFormats: ["gcode"],
    relatedToolIds: ["gcode-viewer", "gcode-visualizer", "gcode-simulator", "gcode-toolpath-viewer", "viewer", "stl-viewer"],
    status: "ready",
  },
  {
    id: "gcode-toolpath-viewer",
    name: "G-code Toolpath Viewer",
    path: "/gcode-toolpath-viewer/",
    category: "viewer",
    description: "Analyze a G-code file's extrusion, travel, tool and feed-rate statistics locally in your browser.",
    inputFormats: ["gcode"],
    relatedToolIds: ["gcode-viewer", "gcode-visualizer", "gcode-simulator", "gcode-layer-viewer", "viewer", "stl-viewer"],
    status: "ready",
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return toolRegistry.find((tool) => tool.id === id);
}
